# Generated by Django 6.0.3 on 2026-03-30 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_habit',
            field=models.IntegerField(default=0, help_text='Количество активных привычек пользователя', verbose_name='Активных привычек'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(blank=True, help_text='Дублируется из модели User для удобства', null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='unknown@example.com', help_text='Дублируется из модели User для удобства', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Автоматически заполняется из имени и фамилии', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
