# Generated by Django 4.1 on 2025-12-03 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit', '0029_remove_habit_num_of_completed_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.ImageField(upload_to='assets/', verbose_name='Файл')),
                ('category', models.CharField(choices=[('icon', 'Иконка'), ('background', 'Фон'), ('logo', 'Логотип')], max_length=50, verbose_name='Категория')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('html_structure', models.TextField(verbose_name='HTML структура')),
                ('css_styles', models.TextField(verbose_name='CSS стили')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Шаблон макета',
                'verbose_name_plural': 'Шаблоны макетов',
            },
        ),
        migrations.CreateModel(
            name='PredefinedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('frequency', models.IntegerField(default=1, verbose_name='Частота')),
                ('period', models.CharField(default='daily', max_length=20, verbose_name='Период')),
                ('goal', models.IntegerField(default=30, verbose_name='Цель (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Шаблон привычки',
                'verbose_name_plural': 'Шаблоны привычек',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('primary_color', models.CharField(default='#262C3C', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#D6BDA8', max_length=7, verbose_name='Вторичный цвет')),
                ('background_color', models.CharField(default='#F3F4F5', max_length=7, verbose_name='Цвет фона')),
                ('font_family', models.CharField(default='Arial', max_length=100, verbose_name='Шрифт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('desktop', 'Компьютер'), ('tablet', 'Планшет'), ('mobile', 'Телефон')], max_length=50, verbose_name='Тип устройства')),
                ('browser', models.CharField(max_length=100, verbose_name='Браузер')),
                ('screen_width', models.IntegerField(verbose_name='Ширина экрана')),
                ('screen_height', models.IntegerField(verbose_name='Высота экрана')),
                ('font_size', models.IntegerField(default=16, verbose_name='Размер шрифта')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка устройства',
                'verbose_name_plural': 'Настройки устройств',
            },
        ),
    ]
