# Generated by Django 6.0.3 on 2026-03-30 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0030_imageasset_layouttemplate_predefinedhabit_theme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-creation_time'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterModelOptions(
            name='streak',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterModelOptions(
            name='tasktracker',
            options={'ordering': ['task_number'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='habit.habit', verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='streak_length',
            field=models.IntegerField(default=0, verbose_name='Длина серии'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(default=1, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(default=90, verbose_name='Цель (дни)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='num_of_tasks',
            field=models.IntegerField(verbose_name='Количество задач'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(max_length=255, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Текущая серия'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='habit.habit', verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='Самая длинная серия'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='num_of_completed_tasks',
            field=models.IntegerField(default=0, verbose_name='Выполнено задач'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='num_of_failed_tasks',
            field=models.IntegerField(default=0, verbose_name='Провалено задач'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='habit.habit', verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='task_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='task_number',
            field=models.IntegerField(verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='task_status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
