# Generated by Django 6.0.3 on 2026-03-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0031_alter_achievement_options_alter_habit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная'), ('monthly', 'Ежемесячная'), ('annual', 'Ежегодная')], max_length=255, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='predefinedhabit',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная'), ('monthly', 'Ежемесячная'), ('annual', 'Ежегодная')], default='daily', max_length=20, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='task_status',
            field=models.CharField(choices=[('In progress', 'В процессе'), ('Completed', 'Выполнено'), ('Failed', 'Провалено')], max_length=255, verbose_name='Статус'),
        ),
    ]
